all: string.o dynamic_array.o function_overloading.o
	g++ -o string string.o
	g++ -o dynamic_array dynamic_array.o
	g++ -o function_overloading function_overloading.o
string.o: string.cc
	g++ -c string.cc
dynamic_array.o: dynamic_array.cc
	g++ -c dynamic_array.cc
function_overloading.o: function_overloading.cc
	g++ -c function_overloading.cc
clean:
	rm string string.o dynamic_array dynamic_array.o function_overloading function_overloading.o
