all: array_pointer.o call_by_reference.o
	g++ -o array_pointer array_pointer.o
	g++ -o call_by_reference call_by_reference.o
array_pointer.o: array_pointer.cc
	g++ -c array_pointer.cc
call_by_reference: call_by_reference.cc
	g++ -c call_by_reference.cc
clean:
	rm array_pointer array_pointer.o call_by_reference call_by_reference.o
