all: prac1.o prac2.o prac3.o prac4.o
	g++ -o prac1 prac1.o
	g++ -o prac2 prac2.o
	g++ -o prac3 prac3.o
	g++ -o prac4 prac4.o
prac1.o: prac1.cc
	g++ -c prac1.cc
prac2.o: prac2.cc
	g++ -c prac2.cc
prac3.o: prac3.cc
	g++ -c prac3.cc
prac4.o: prac4.cc
	g++ -c prac4.cc
clean:
	rm prac1 prac1.o prac2 prac2.o prac3 prac3.o prac4 prac4.o
